[package]
name = "ks89-producer"
version = "4.0.0"
edition = "2024"
resolver = "3"

[[bin]]
name = "producer"
path = "src/main.rs"

[lib]
name = "producer"
path = "src/lib.rs"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[dependencies]
lapin = { version = "4.10.0" }
tokio = { version = "^1.52.3", features = ["full"] }
paho-mqtt = "0.14.0"
futures = "^0.3.32"
hmac = "^0.13.0"
sha2 = "^0.11.0"
hex = "^0.4.3"
zeroize = { version = "^1.8.2", features = ["serde"] }
uuid = { version = "^1.23.1", features = ["v4", "fast-rng"] }
# error handling
thiserror = "2.0.18"
anyhow = "1.0.102"
# logger
tracing = "^0.1.44"
tracing-subscriber = { version = "^0.3.23", features = ["env-filter"] }
tracing-appender = "^0.2.5"
# env vars
dotenvy = "^0.15.7"
envy = "^0.4.2"

# To use Serialize and Deserialize traits, you must include Serde.
# The "derive" feature is only required when
# using #[derive(Serialize, Deserialize)] to make Serde work with structs
# and enums defined in your crate.
serde = { version = "^1.0.228", features = ["derive"] }
serde_json = "^1.0.150"

[dev-dependencies]
# better looking rust assertions
pretty_assertions = "^1.4.1"
# include also serde_json with the feature 'preserve_order' to don't change the order of keys
# 'preserve_order' is required to compare results in a predictible way in testing
serde_json = { version = "^1.0.150", features = ["preserve_order"] }
test-log = {version = "0.2.20", features = ["trace"]}
